name: sync_deps

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync_glext
        run: |
            cd $GITHUB_WORKSPACE
            bash ./pkg/glext/sync.sh

