name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  win-msvc:

    runs-on: windows-latest

    steps:
      - name: Install dependencies via vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgGitCommitId: 595777db2332a3442b73f9af9f656355f207aec9
          vcpkgTriplet: x64-windows
          vcpkgArguments: pthreads sdl2

      - name: vcpkg integrate install
        shell: cmd
        run: |
          cd vcpkg && vcpkg.exe integrate install
