name: 'test vcpkg'

on:
  workflow_dispatch:

jobs:
  win-msvc:

    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

      - name: Restore vcpkg binary cache archives
        id: restore_vcpkg_binary_cache
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: vcpkg-binary-cache
        
      - name: Install dependencies via vcpkg
        run: |
          cd /mnt/c/vcpkg
          ./vcpkg.exe install pthreads:x64-windows

