name: 'tests Windows'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  win-msvc:

    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

#      - name: Setup tmate
#        if: always()
#        run: |
#          sudo apt -y update
#          #Install tmate
#          sudo apt-get install -y tmate openssh-client
#          # Generate ssh key if needed
#          [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
#          # Run deamonized tmate
#          echo Running tmate...
#          tmate -S /tmp/tmate.sock new-session -d
#          tmate -S /tmp/tmate.sock wait tmate-ready
#          # Print connection info
#          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
#          
#          # Wait for connection
#          while [ -S /tmp/tmate.sock ]; do
#            sleep 1
#          done
