name: 'test vcpkg'

on:
  workflow_dispatch:

jobs:
  win-msvc:

    runs-on: windows-latest

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

      - name: Restore vcpkg binary cache archives
        id: restore vcpkg binary cache archives
        uses: actions/cache@v2
        with:
        path: C:\Users\runner\AppData\Local\vcpkg\archives
        key: vcpkg-binary-cache
        
      - name: Install dependencies via vcpkg
        run: |
          git clone git@github.com:microsoft/vcpkg.git
          git checkout 595777db2332a3442b73f9af9f656355f207aec9
          cd vcpkg
          ./bootstrap-vcpkg.exe
          ./vcpkg.exe install shaderc:x64-windows

